# Generated by Django 4.1.7 on 2023-04-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='document_type',
            field=models.CharField(choices=[('letter', 'Lettre'), ('ordonance', 'Ordonance'), ('mission', 'Ordre de mission')], default='letter', max_length=255, null=True),
        ),
    ]
