# Generated by Django 4.1.7 on 2023-04-03 03:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documents_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='id',
            field=models.UUIDField(default=uuid.UUID('646ed656-f4b1-45e3-a886-fa133ebc91b0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
