# Generated by Django 4.1.7 on 2023-04-03 03:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documents_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1245a217-4f19-4035-81b7-6c07072e3366'), editable=False, primary_key=True, serialize=False),
        ),
    ]
