# Generated by Django 4.1.7 on 2023-04-03 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('content', models.TextField(blank=True, max_length=10000, null=True)),
                ('status', models.CharField(choices=[('waiting', 'En Attente'), ('validated', 'Validée'), ('rejected', 'En Attente')], default='waiting', max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de mise à jour')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
    ]
