# Generated by Django 4.1.7 on 2023-04-03 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_documents_id'),
        ('requests', '0003_alter_requests_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='from_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.documents'),
        ),
    ]
